version: '3.8'
services:
  reviews_service:
    build: ./ReviewsService
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:h2:file:./data/reviews_service;MV_STORE=FALSE;AUTO_SERVER=true;
      - spring.datasource.driverClassName=org.h2.Driver
      - spring.datasource.username=sa
      - spring.datasource.password=gg
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2-console
    volumes:
      - ./data:/data

  votes_service:
          build: ./VotesService
          ports:
            - "8081:8081"
          environment:
            - spring.datasource.url=jdbc:h2:file:./data/votes_service;MV_STORE=FALSE;AUTO_SERVER=true;
            - spring.datasource.driverClassName=org.h2.Driver
            - spring.datasource.username=sa
            - spring.datasource.password=gg
            - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
            - spring.h2.console.enabled=true
            - spring.h2.console.path=/h2-console
          volumes:
            - ./data:/data
