version: '3.8'
services:
  products_service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:h2:file:./data/products_service;MV_STORE=FALSE;AUTO_SERVER=true;
      - spring.datasource.driverClassName=org.h2.Driver
      - spring.datasource.username=sa
      - spring.datasource.password=gg
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2-console
    volumes:
      - ./data:/data
