@startuml
!theme plain

package "Review Service" {
    package "Controller"
    package "Mapper"
    package "Service"
    package "DTO"
    package "Model" {
        package "Document Models"
        package "Relational Models"
        package "Graph Models"
    }
    package "Repository" {
        package "Relational"
        package "Graph"
        package "Document"
    }
}

[Controller] ..> [Service]
[Controller] ..> [Mapper]
[Controller] ..> [DTO]
[Service] .up.> [Mapper]
[Service] ..> [Repository]
[Repository] ..> Model
Model ..> [DTO]

@enduml
