@startuml
!theme plain

Component ReviewService {
    Port "8083" as port8083

    Package Controller {
        component "Review Controller" as ReviewCtrl <<class>>
    }
    Package Service {
        component "Review Service" as ReviewSvc <<interface>>
        component "Review Service Impl" as ReviewSvcImpl <<class>>
        component "Rating Service" as RatingSvc <<interface>>
        component "Rating Service Impl" as RatingSvcImpl <<class>>
    }
    Package DTO {
        component "Review DTO" as ReviewDTO <<class>>
        component "Rating DTO" as RatingDTO <<class>>
    }
    Package Mapper {
        component "Review Mapper" as ReviewMapper <<class>>
    }
    Package Model {
        component "Review Model" as ReviewModel <<class>>
        component "Rating Model" as RatingModel <<class>>
        Package "document" as ReviewModelDocument {
            component "Review Model Mongo" as ReviewModelMongo <<class>>
            component "Rating Model Mongo" as RatingModelMongo <<class>>
        }
        Package "relational" as ReviewModelRelational {
            component "Review Model JPA" as ReviewModelJPA <<class>>
            component "Rating Model JPA" as RatingModelJPA <<class>>
        }
        Package "graph" as ReviewModelGraph {
            component "Review Model Neo4j" as ReviewModelNeo4j <<class>>
            component "Rating Model Neo4j" as RatingModelNeo4j <<class>>
        }
    }
    Package Repository {
        component "Rating Repository" as RatingRepo <<interface>>
        component "Review Repository" as ReviewRepo <<interface>>
        Package "document" {
            component "Review Repository Mongo" as ReviewRepoMongo <<interface>>
            component "Review Repository Document" as ReviewRepoDocument <<class>>
            component "Rating Repository Mongo" as RatingRepoMongo <<interface>>
            component "Rating Repository Document" as RatingRepoDocument <<class>>
        }
        Package "relational" {
            component "Review Repository JPA" as ReviewRepoJPA <<interface>>
            component "Review Repository Relational" as ReviewRepoRelational <<class>>
            component "Rating Repository JPA" as RatingRepoJPA <<interface>>
            component "Rating Repository Relational" as RatingRepoRelational <<class>>
        }
        Package "graph" {
            component "Review Repository Neo4j" as ReviewRepoNeo4j <<interface>>
            component "Review Repository Graph" as ReviewRepoGraph <<class>>
            component "Rating Repository Neo4j" as RatingRepoNeo4j <<interface>>
            component "Rating Repository Graph" as RatingRepoGraph <<class>>
        }
    }
    Package "DB Driver" {
        component "MongoDB Driver" as MongoDriver <<driver>>
        component "Neo4j Driver" as Neo4jDriver <<driver>>
        component "H2 Driver" as H2Driver <<driver>>
    }

    Port "27017" as portMongo
    Port "7687" as portNeo4j
}

database "Review Database" as ReviewDB <<database>>

port8083 -up- "REST API" : exposes

ReviewCtrl -up- port8083

RatingSvcImpl -down-> RatingSvc : implements
ReviewSvcImpl -down-> ReviewSvc : implements
ReviewSvcImpl -up-> ReviewMapper : uses

ReviewCtrl -down-> ReviewSvcImpl : uses
ReviewCtrl -down-> RatingSvcImpl : uses
ReviewCtrl -left-> ReviewDTO : manipulates
ReviewCtrl -left-> RatingDTO : manipulates
ReviewSvcImpl -down-> ReviewDTO : data transfer
RatingSvcImpl -down-> RatingDTO : data transfer


ReviewRepoRelational -up-> ReviewRepo : implements
ReviewRepoDocument -up-> ReviewRepo : implements
ReviewRepoGraph -up-> ReviewRepo : implements

RatingRepoRelational -up-> RatingRepo : implements
RatingRepoDocument -up-> RatingRepo : implements
RatingRepoGraph -up-> RatingRepo : implements

ReviewRepoDocument -down-> ReviewRepoMongo : uses
ReviewRepoRelational -down-> ReviewRepoJPA : uses
ReviewRepoGraph -down-> ReviewRepoNeo4j : uses

RatingRepoDocument -down-> RatingRepoMongo : uses
RatingRepoRelational -down-> RatingRepoJPA : uses
RatingRepoGraph -down-> RatingRepoNeo4j : uses

ReviewSvcImpl -down-> ReviewRepo : interacts with
ReviewRepo -down-> ReviewModel : manipulates
ReviewRepoMongo -down-> ReviewModelMongo : manipulates
ReviewRepoJPA -down-> ReviewModelJPA : manipulates
ReviewRepoNeo4j -down-> ReviewModelNeo4j : manipulates

RatingSvcImpl -down-> RatingRepo : interacts with
RatingRepo -down-> RatingModel : manipulates
RatingRepoMongo -down-> RatingModelMongo : manipulates
RatingRepoJPA -down-> RatingModelJPA : manipulates
RatingRepoNeo4j -down-> RatingModelNeo4j : manipulates

ReviewRepoDocument -down--> MongoDriver : uses
RatingRepoDocument -down--> MongoDriver : uses
ReviewRepoGraph -down--> Neo4jDriver : uses
RatingRepoGraph -down--> Neo4jDriver : uses
ReviewRepoRelational -down--> H2Driver : uses
RatingRepoRelational -down--> H2Driver : uses

H2Driver -down-> ReviewDB : persists to

MongoDriver -down-> portMongo : connects to
Neo4jDriver -down-> portNeo4j : connects to

portMongo -down-> ReviewDB : persists to
portNeo4j -down-> ReviewDB : persists to

ReviewSvcImpl -left-> "Numbers API" : uses

ReviewSvcImpl -down--> ReviewModel : interacts with
RatingSvcImpl -down--> RatingModel : interacts with

@enduml
