version: '3.8'
services:
  reviews_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:h2:file:./data/reviews_service;MV_STORE=FALSE;AUTO_SERVER=true;
      - spring.datasource.driverClassName=org.h2.Driver
      - spring.datasource.username=sa
      - spring.datasource.password=gg
      - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2-console
    volumes:
      - ./data:/data
    depends_on:
      - database

  database:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - /path/to/local/data_dir:/opt/h2-data
      - ./data:/data
    environment:
      - H2_OPTIONS=-ifNotExists
    container_name: MyH2Instance
